services:
  - type: web
    name: telegram-ai-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node webhook-bot.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: 10000
